### ISSUE TITLE
ConcurrnetHashMap 을 사용하세요.

### ISSUE THREAD

**Issue by jslee0086** [dae0hwang/HTTPServer#1]
예전에 직접 조사도 하셨겠지만, 특수한 목적이 없는 이상 Concurrnet 컨테이너를 사용하는것이 일반적입니다.
Lock 범위를 크게 확장해야 할 때만 사용하세요.

https://github.com/dae0hwang/HTTPServer/blob/fd49f4afbed2db1292f41a95f32a33c44ee979ce/SimpleHTTP/src/main/java/StringStorage.java#L8

**Comment by dae0hwang** [comment]
변경 완료했습니다.
