### ISSUE TITLE
특별한 목적이 없는이상 static 변수는 사용하지 마세요.

### ISSUE THREAD

**Issue by jslee0086** [dae0hwang/HTTPServer#2]
static 처럼 전역에 단 하나의 데이터만 존재해야 하는 데이터는 극히 특수한 경우에만 사용합니다.

https://github.com/dae0hwang/HTTPServer/blob/fd49f4afbed2db1292f41a95f32a33c44ee979ce/SimpleHTTP/src/main/java/StringStorage.java#L6

**Comment by dae0hwang** [comment]
변경 완료했습니다.
